### ISSUE TITLE
skip gender

### ISSUE THREAD

**Issue by LazloDB** [diegoisawesome/GBAIntroManager#1]
When I toggle the skip gender, the introscreen (with gengar and nidorino) keeps repeating. 
Do you know how I can fix this?

**Comment by Sierraffinity** [comment]
I can't replicate this issue on any supported ROMs but something similar happens on a FireRed V1.1 ROM. Are you using V1.1 or V1.0?

**Comment by LazloDB** [comment]
Yeah it's on FireRed v1.1. My bad.
It's fine on Emerald.

**Comment by Sierraffinity** [comment]
I'll try to release a version of this program sometime in the future that supports v1.1, even though it's less common.
