### ISSUE TITLE
The "Start Position" changer doesn't work on Pokémon Emerald (BPRE)

### ISSUE THREAD

**Issue by LOuroboros** [diegoisawesome/GBAIntroManager#4]
I know this tool is no longer in development, but I thought I should still open up an issue to document the problem anyway.
When I tried the Start Position changing feature that the program has on a clean Pokémon Emerald ROM, it didn't work on my end.
I'm using the v0.1.4, the latest version available in **[the Releases page of this repository](https://github.com/Sierraffinity/GBAIntroManager/releases)**.

The steps that I did were:
**1**) Open a Pokémon Emerald ROM with the program _(sha1: f3ae088181bf583e55daf962a92bb46f4f1d07b7)_
**2**) Hit the "Unlock" button under the "X Y" fields.
**3**) Set the Bank and Map to 32 and 00 respectively _(the Weather Institute near Fortree City.)_
**4**) Changed the X and Y coordinates to the desired location _(X5 and Y6)_
**5**) File > Save
**6**) I tested the ROM in both, VisualBoyAdvance and mGBA. The game freezes at the end of Birch's introduction.

![Game](https://user-images.githubusercontent.com/4485172/95046787-3f903b00-06bb-11eb-8972-f80bdd298f37.png)

**Comment by Sierraffinity** [comment]
Line 8 of the readme:

> NOTE: ALL VALUES ARE IN HEXADECIMAL UNLESS OTHERWISE NOTED.

AdvanceMap's bank & map numbers are in decimal, so you'd need to use bank 0x20, map 0x00.
